// File generated by flutterfire configure tool.
// Verified: Dependencies are resolved.
// DO NOT EDIT by hand. Instead, run flutterfire configure to update.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (Platform.operatingSystem) {
      case 'android':
        return android;
      case 'ios':
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhte7JjjKWxSqJR6zmwfz9z4mJd2A-QQM',
    appId: '1:337492275214:android:2995cdf0ef44ed29a94c5f',
    messagingSenderId: '337492275214',
    projectId: 'bahay-kusina-main',
    databaseURL: 'https://bahay-kusina-main.firebaseio.com',
    storageBucket: 'bahay-kusina-main.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDywGt32je6zmuFjaRdycEmd8cdvlllu8A',
    appId: '1:337492275214:web:b85c2222c78f5c4ea94c5f',
    messagingSenderId: '337492275214',
    projectId: 'bahay-kusina-main',
    authDomain: 'bahay-kusina-main.firebaseapp.com',
    databaseURL: 'https://bahay-kusina-main.firebaseio.com',
    storageBucket: 'bahay-kusina-main.firebasestorage.app',
    measurementId: 'G-P8C2E3TSBJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkM9Ic4m1kyZMnUti0P91POPIaO6-Ob-M',
    appId: '1:337492275214:ios:2995cdf0ef44ed29ios',
    messagingSenderId: '337492275214',
    projectId: 'bahay-kusina-main',
    authDomain: 'bahay-kusina-main.firebaseapp.com',
    databaseURL: 'https://bahay-kusina-main.firebaseio.com',
    storageBucket: 'bahay-kusina-main.firebasestorage.app',
    iosBundleId: 'com.example.bahaykusina',
  );
}
